HELM_FLINK_REPO: str = 'https://downloads.apache.org/flink/flink-kubernetes-operator-'
HELM_MINIO_REPO: str = 'https://operator.min.io'
HELM_SCYLLA_REPO: str = 'https://storage.googleapis.com/scylla-operator-charts/stable'
HELM_SPARK_REPO: str = 'https://kubeflow.github.io/spark-operator'
HELM_KAFKA_REPO: str = 'https://strimzi.io/charts/'