apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pipeline-spark-redpanda
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "santrac10/pipeline-spark-redpanda:latest"
  imagePullPolicy: Always
  mainClass: com.redpanda.examples.spark.RedpandaSparkStream
  mainApplicationFile: "local:///app/target/scala-2.12/RedpandaSparkStream-assembly-1.0.0.jar"
  sparkVersion: "3.1.3"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.3
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.3
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"